# Change these first
owner: dencap
repo: Upptime

sites:
  - name: DENCAP Main Website
    url: https://www.dencap.com
  - name: DENCAP Payment Portal
    url: https://pay.dencapsecure.com
  - name: Healthy Michigan Dental
    url: https://hmidental.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /Upptime
  logoUrl: https://pay.dencapsecure.com/favicon/apple-touch-icon.png
  name: DENCAP Dental Plans
  introTitle: 
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
