# Change these first
owner: dencap
repo: Upptime

sites:
  - name: DC Main
    url: https://www.dencap.com
  - name: DC Payment Portal
    url: https://pay.dencapsecure.com
  - name: DC Doc Portal-Agent
    url: https://agents.dencapsecure.com
  - name: DC Doc Portal-Provider
    url: https://providers.dencapsecure.com
  - name: HMD Main
    url: https://hmidental.com
  - name: HMD Doc Portal
    url: https://hmdsecure.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /Upptime
  logoUrl: https://pay.dencapsecure.com/favicon/apple-touch-icon.png
  name: DENCAP Dental Plans
  introTitle: 
  theme: dark
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
